version: "3.7"
services:
  web-server:
    build:
      dockerfile: php.Dockerfile
      context: .
    restart: always
    command: --init-file /data/application/init.sql
    volumes:
      - "./html/:/var/www/html/"
    ports:
      - "8080:80"
  mysql-server:
    image: mysql:8.0.19
    restart: always
    command: --init-file /data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: 'kabum'
    volumes:
      - ./init.sql:/data/application/init.sql
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mysql-server
      PMA_USER: root
      PMA_PASSWORD: admin123
    ports:
      - "5000:80"
volumes:
  mysql-data: