CREATE DATABASE IF NOT EXISTS kabum;
USE kabum;

CREATE TABLE IF NOT EXISTS `kabum`.`Users_` ( 
  `id` INT NOT NULL AUTO_INCREMENT , 
  `name` VARCHAR(255) NOT NULL , 
  `email` VARCHAR(255) NOT NULL , 
  `password` VARCHAR(255) NOT NULL , 
  `CREATED_AT` INT NOT NULL DEFAULT CURRENT_TIMESTAMP , 
  `UPDATED_AT` INT NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP , 
  PRIMARY KEY (`id`), 
  UNIQUE (`email`)
)ENGINE = InnoDB;