CREATE DATABASE IF NOT EXISTS kabum;
USE kabum;

CREATE TABLE `kabum`.`Users` ( 
  `id` INT NOT NULL AUTO_INCREMENT , 
  `name` VARCHAR(255) NOT NULL , 
  `email` VARCHAR(255) NOT NULL , 
  `password` VARCHAR(255) NOT NULL , 
  `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , 
  `UPDATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
  PRIMARY KEY (`id`), 
  UNIQUE (`email`)
);
